config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'welcome#index'
  root 'surveys#index'

  resources :surveys do
    resources :mcqs, only: [:new, :create, :destroy]
    resources :nrqs, only: [:new, :create, :destroy]
    resources :responses, only: [:new, :create]
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, polymorphic: true
  belongs_to :response, optional: true
  validates :answer_entry,
            presence: { message: 'You must select at least one option below' }, if: :required_question?

  attr_accessor :checked

  def required_question?
    question.required
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mcq.rb
class Mcq < ApplicationRecord
  has_many :options, dependent: :destroy
  has_many :answers, as: :question, dependent: :destroy
  belongs_to :survey

  attr_writer :current_step
  attr_accessor :option_count

  accepts_nested_attributes_for :options
  validates :question_text, presence: true

  def current_step
    @current_step || steps.first
  end

  def steps
    %w[setup options]
  end

  def next_step
    self.current_step = steps[steps.index(current_step) + 1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step) - 1]
  end

  def last_step?
    current_step == steps.last
  end
end

app/models/nrq.rb
class Nrq < ApplicationRecord
  belongs_to :survey
  has_many :answers, as: :question, dependent: :destroy

  validates :question_text, presence: true
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :mcq, optional: true
  validates :option_text, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :survey, counter_cache: true

  accepts_nested_attributes_for :answers

  def remove_blanks
    blank_ans = answers.select { |ans| ans[:answer_entry].nil? }
    answers.destroy(blank_ans)
  end

  def sorted_answers
    answers.sort_by(&:question_id)
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :mcqs, -> { includes :options }, dependent: :destroy
  has_many :nrqs, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :answers, through: :responses

  validates :title, presence: true, uniqueness: true

  attr_accessor :question_type
  QUESTION_TYPES = ['Multiple Choice', 'Number Range'].freeze

  def questions?
    (mcqs.any? || nrqs.any?)
  end

  def result_count
    results = {}
    answers.group_by { |a| [a.question_id, a.answer_entry, a.question_type] }
           .map { |k, v| results[k] = v.length }
    results
  end

  def question_details
    questions = {}
    mcqs.map { |m| questions[[m.id, 'Mcq']] = { question_text: m.question_text, required: m.required, multiselect: m.multiselect, options: m.options } }
    nrqs.map { |n| questions[[n.id, 'Nrq']] = { question_text: n.question_text, required: n.required, min: n.min, max: n.max } }
    questions
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mcqs_controller.rb
class McqsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @mcq = Mcq.new
    session[:mcq_params] = {} # initialize session
  end

  def create
    @survey = Survey.find(params[:survey_id])

    # save current params to session
    session[:mcq_params].deep_merge!(mcq_params) if params[:mcq]

    @mcq = Mcq.new(session[:mcq_params])
    @mcq.survey_id = params[:survey_id]
    @mcq.current_step = session[:mcq_step]

    # If there are no options for @mcq or
    # if the option count is updated, build @mcq.options
    if @mcq.option_count.to_i != @mcq.options.length
      @mcq.options = []
      @mcq.option_count.to_i.times { @mcq.options.build }
    end

    if params[:previous_button]
      @mcq.previous_step
    elsif @mcq.last_step?
      @mcq.save if @mcq.valid?
    else
      @mcq.next_step
    end

    session[:mcq_step] = @mcq.current_step

    # if @mcq is not saved, render 'new'
    if @mcq.new_record?
      render 'new'
    else # if @mcq is saved clear session and redirect
      session[:mcq_step] = session[:mcq_params] = nil
      redirect_to edit_survey_path(@mcq.survey_id)
    end
  end

  def destroy
    @mcq = Mcq.find(params[:id])
    @mcq.destroy

    redirect_back(fallback_location: root_path) # refresh the page after delete
  end

  private

  def mcq_params
    params.require(:mcq)
          .permit(:option_count, :question_text, :multiselect, :required, options_attributes: [:option_text])
  end
end

app/controllers/nrqs_controller.rb
class NrqsController < ApplicationController
  def new
    @survey = Survey.find(params[:survey_id])
    @nrq = Nrq.new
  end

  def create
    @nrq = Nrq.new(nrq_params)
    @nrq.survey_id = params[:survey_id]
    if @nrq.save
      redirect_to edit_survey_path(@nrq.survey_id)
    else
      @survey = Survey.find(params[:survey_id])
      render :new
    end
  end

  def destroy
    @nrq = Nrq.find(params[:id])
    @nrq.destroy
    redirect_to :back
  end

  private

  def nrq_params
    params.require(:nrq).permit(:question_text, :min, :max, :required)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_action :set_survey, only: [:new, :create]

  def new
    @response = Response.new

    @survey.mcqs.each { |mcq| @response.answers.build(question_id: mcq.id, question_type: 'Mcq') }
    @survey.nrqs.each { |nrq| @response.answers.build(question_id:nrq.id, question_type: 'Nrq') }
    @questions = @survey.question_details
  end

  def create
    @response = Response.new(response_params)
    @response.survey_id = @survey.id

    build_checkbox_answers

    if @response.valid?
      @response.remove_blanks
      @response.save
      redirect_to root_path
    else
      rebuild_form
      @questions = @survey.question_details
      render :new
    end
  end

  private

  def response_params
    params.require(:response).permit(answers_attributes:
      [:question_id, :question_type, :answer_entry, answer_entry: []])
  end

  def build_checkbox_answers
    response_params[:answers_attributes].values.each do |a|
      if (a[:answer_entry].is_a? Array) && (a[:answer_entry] != [''])
        a[:answer_entry] -= ['']

        a[:answer_entry].map { |answer| @response.answers.build(  question_id: a[:question_id],
          question_type: a[:question_type],
          answer_entry: answer
        )}

        parent_answer = @response.answers.find{ |ans| ans[:question_id] == a[:question_id].to_i && ans[:answer_entry].nil? }
        @response.answers.destroy(parent_answer) if parent_answer
      end
    end
  end

  def rebuild_form
    mcq_ans = @response.answers.select{|ans| ans[:question_type] == 'Mcq'}

    checked = Hash.new { |hash, key| hash[key] = [] }
    mcq_ans.map do |m|
      checked[m.question_id] << m.answer_entry if m.answer_entry
      @response.answers.destroy(m) if checked[m.question_id].length > 1
    end

    @response.answers.each { |ans| ans.checked = checked[ans.question_id] }
  end

  def set_survey
    @survey = Survey.find(params[:survey_id])
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update]

  def index
    @surveys = Survey.all.includes(:mcqs, :nrqs, :responses)
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      redirect_to edit_survey_path(@survey.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if params[:survey][:question_type] == '0'
      session[:current_step] = session[:mcq_params] = nil
      redirect_to new_survey_mcq_path(@survey.id)
    elsif params[:survey][:question_type] == '1'
      redirect_to new_survey_nrq_path(@survey.id)
    end
  end

  def show
    @mcqs = @survey.mcqs
    @nrqs = @survey.nrqs
    @results = @survey.result_count
  end

  private

  def survey_params
    params.require(:survey).permit(:title, :description)
  end

  def set_survey
    @survey = Survey.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mcqs_helper.rb
module McqsHelper
end

app/helpers/nrqs_helper.rb
module NrqsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Surveyor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/mcqs/_mcq_options.html.erb
<div class="sub-menu">

  <span class="inactive">1. Select Options</span> | <span class="active">2. Add Question Text</span>

</div>

<div class="response-count padding">Next, add the text for each of your options.</div>

<%= form_for [survey, mcq] do |f| %>

  <%= f.label :question_text, 'What is your question?' %>
  <%= f.text_field :question_text, placeholder: 'eg. "Who does Number Two work for?"'%>

  <%= f.fields_for :options do |option_fields| %>

    <%= option_fields.label :option_text, "Option #{option_fields.options[:child_index] + 1}:" %>

    <%= option_fields.text_field :option_text, placeholder: 'eg. "Dr. Evil"'%>

  <% end %>

  <%= f.submit "Add Question", class: 'btn btn-primary btn-lg btn-block' %>

  <%= f.submit "Back to previous step", name: 'previous_button', class: 'btn-link underline' %>

<% end %>

app/views/mcqs/_mcq_setup.html.erb
<div class="sub-menu">
  <span class="active">1. Select Options</span> | <span class="inactive">2. Add Question Text</span>
</div>

<div class="form-container">

  <%= form_for [survey, mcq] do |f| %>

    <div class="form-row">
      <div class="response-count">How many options should the question have?</div>
      <%= f.select(:option_count, (2..5)) %>
    </div>

    <div class="form-row">
      <div class="response-count">How many options can be selected?</div>

      <div class="option">
        <%= f.radio_button :multiselect, 'false', checked: true %>
        <%= f.label :multiselect, 'Just One', value: 'false' %>
      </div>

      <div class="option">
        <%= f.radio_button :multiselect, 'true' %>
        <%= f.label :multiselect, 'Multiple', value: 'true' %>
      </div>
    </div>

    <div class="form-row">
      <div class="response-count">Is the question required?</div>

      <div class="option">
        <%= f.radio_button :required, 'true', checked: true %>
        <%= f.label :required, 'Yes', value: 'true' %>
      </div>

      <div class="option">
        <%= f.radio_button :required, 'false' %>
        <%= f.label :required, 'No', value: 'false' %>
      </div>

    </div>

    <%= f.submit "Continue to the Next Step", class: 'btn btn-primary btn-lg btn-block' %>

  <% end %>

</div>

app/views/mcqs/new.html.erb
<%= render 'shared/nav' %>

<%= render 'shared/header', class_name1: 'inactive', class_name2: 'active' %>

<%= render 'shared/survey_content', survey: @survey, class_name: "inactive" %>

<hr>

<div class="sub-heading">Add a Multiple Choice Question:</div>

<%= render "mcq_#{@mcq.current_step}", survey: @survey, mcq: @mcq %>

<hr>

<%= render 'shared/existing_questions', class_name: "inactive"  %>

app/views/nrqs/new.html.erb
<%= render 'shared/nav' %>

<%= render 'shared/header', class_name1: 'inactive', class_name2: 'active' %>

<%= render 'shared/survey_content', survey: @survey, class_name: "inactive" %>

<hr>

  <div class="sub-heading">Add a Number Range Question:</div>

  <div class="form-container">

    <%= form_for [@survey, @nrq] do |f| %>

      <%= f.label :question_text, 'What is your question?' %>
      <%= f.text_field :question_text, placeholder: 'eg. "How many times per day do you blink?"'%>

      <div class="form-row">
        <div class="response-count">What is the Minimum Range Value?</div>
        <%= f.select(:min, (1..5)) %>
      </div>

      <div class="form-row">
        <div class="response-count">What is the Maximum Range Value?</div>
        <%= f.select(:max, (6..10)) %>
      </div>

      <div class="form-row">
        <div class="response-count">Is the question required?</div>

        <div class="option">
          <%= f.radio_button :required, 'true', checked: true %>
          <%= f.label :required, 'Yes', value: 'true' %>
        </div>

        <div class="option">
          <%= f.radio_button :required, 'false' %>
          <%= f.label :required, 'No', value: 'false' %>
        </div>
      </div>

      <%= f.submit "Add Question", class: 'btn btn-primary btn-lg btn-block' %>

    <% end %>

  </div>

<hr>

<%= render 'shared/existing_questions', class_name: "inactive"  %>

app/views/responses/_mcq_answer.html.erb
<% if @questions[[form.object.question_id, 'Mcq']][:multiselect] %>
  <%= form.collection_check_boxes(:answer_entry, @questions[[form.object.question_id, 'Mcq']][:options], :id, :option_text, checked: form.object.checked) do |b| %>
    <%= b.label { b.check_box + b.text } %>
  <% end %>
<% else %>
  <%= form.collection_radio_buttons(:answer_entry, @questions[[form.object.question_id, 'Mcq']][:options], :id, :option_text) do |b| %>
    <%= b.label { b.radio_button + b.text } %>
  <% end %>
<% end %>

app/views/responses/_nrq_answer.html.erb
<span class="float-left"><%= @questions[[form.object.question_id, 'Nrq']][:min] %></span>
<span class="float-left">
  <%= form.range_field(:answer_entry, in: @questions[[form.object.question_id, 'Nrq']][:min]..@questions[[form.object.question_id, 'Nrq']][:max]) %>
</span>
<span class="float-left"><%= @questions[[form.object.question_id, 'Nrq']][:max] %></span>

app/views/responses/new.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/response_header', survey: @survey, title_text: "Taker" %>

<div class="response-count inactive">Questions marked with an asterisk (*) are required</div>

<div class="response-form">
  <%= form_for [@survey, @response] do |f| %>

    <%= f.fields_for :answers, f.object.sorted_answers do |a| %>

      <div class="response-field">

        <div class="question-text">
          <span class="required"><%= '* ' if @questions[[a.object.question_id, a.object.question_type]][:required] %></span>
          <%= a.options[:child_index] + 1 %>.

          <%= @questions[[a.object.question_id, a.object.question_type]][:question_text] %>
        </div>
        <% unless a.object.errors[:answer_entry].blank? %>
          <div class="error-msg">
            <%= a.object.errors[:answer_entry].first %>
          </div>
          <div class="answer-box error-box">
        <% else %>
          <div class="answer-box">
        <% end %>
          <%= a.hidden_field :question_type %>
          <%= a.hidden_field :question_id %>
          <%= render "#{a.object.question_type.downcase}_answer", form: a
          %>
        </div>
      </div>

    <% end %>
  <%= submit_tag "Create Your Survey", class: 'btn btn-primary btn-lg btn-block' %>
  <% end %>
</div>

app/views/shared/_existing_questions.html.erb
<div class="questions <%= class_name %>">

  <div class="sub-heading">Existing Questions:</div>

  <% unless @survey.questions? %>

    <div class="description">There are no questions yet!</div>

  <% else %>

    <ol>
      <%= render partial: 'shared/mcq', locals: {survey: @survey}, collection: @survey.mcqs, as: :mcq %>

      <%= render partial: 'shared/nrq', locals: {survey: @survey}, collection: @survey.nrqs, as: :nrq %>
    </ol>

    <hr>

    <%= link_to "Finish Building Survey and Return", root_path, {:class=>"btn btn-primary btn-lg btn-block" }  %>

  <% end %>

</div>

app/views/shared/_header.html.erb
<header>
  <h1>Survey Builder</h1>
  <hr>

  <div class="sub-menu">
    <span class='<%= class_name1 %>'> 1. Build Survey </span> |
    <span class='<%= class_name2 %>'> 2. Add Questions </span>
  </div>
</header>

app/views/shared/_mcq.html.erb
<li>
  <%= mcq.question_text %>

  <div class="survey-content">

    <% if mcq.required %>
      <span class="response-count">Required.</span>
    <% else %>
      <span class="response-count">Not Required.</span>
    <% end %>

    <% if mcq.multiselect %>
      <span class="response-count">Select Multiple.</span>
    <% else %>
      <span class="response-count">Select One.</span>
    <% end %>

  </div>

  <ol type="a">

  <% mcq.options.each do |o| %>
    <li><%= o.option_text %></li>
  <% end %>

  </ol>

  <%= link_to "Remove Question", [survey, mcq], method: :delete, data: {confirm: 'Delete this question?'}, class: :underline %>

</li>

app/views/shared/_nav.html.erb
<%= link_to "Back to Home", root_path, class: :underline %>

app/views/shared/_nrq.html.erb
<li>
  <%= nrq.question_text %>

  <div class="survey-content">

    <% if nrq.required %>
      <span class="response-count">Required.</span>
    <% else %>
      <span class="response-count">Not Required.</span>
    <% end %>

    <br>

    <span class="response-count">Minimum : <%= nrq.min %>,</span>
    <span class="response-count">Maximum : <%= nrq.max %></span>

  </div>

  <%= link_to "Remove Question", [survey, nrq], method: :delete, data: {confirm: 'Delete this question?'}, class: :underline %>

</li>

app/views/shared/_response_header.html.erb
<header>
  <h1>Survey <%= title_text %>:</h1>
  <hr>
  <div class="sub-heading"><center><%= survey.title %></center></div>
  <p class="description"><%= survey.description %></p>
</header>

app/views/shared/_survey_content.html.erb
<div class="survey-content <%= class_name %>">
  <div class="sub-heading">Title:</div>
  <div class="description"><%= survey.title %></div>

  <div class="sub-heading">Description:</div>
  <div class="description"><%= survey.description %></div>
</div>

app/views/surveys/_mcq_result.html.erb
<li>
  <%= mcq.question_text %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Response</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      <% mcq.options.each do |op| %>
        <tr>
          <td><%= op.option_text %></td>
          <td><%= @results[[mcq.id, op.id, 'Mcq']].to_i %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</li>

app/views/surveys/_nrq_result.html.erb
<li>
  <%= nrq.question_text %>
  <table class="table table-striped table-no-border">
    <thead>
      <tr>
        <th>Response</th>
        <th>Count</th>
      </tr>
    </thead>
    <tbody>
      <% (nrq.min..nrq.max).each do |n| %>
        <tr>
          <td><%= n %></td>
          <td><%= @results[[nrq.id, n, 'Nrq']].to_i %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</li>

app/views/surveys/_survey.html.erb
<li>
  <%= survey.title %>
  <div class="survey-content">
    <div class="description">
      <%= survey.description %>
    </div>

    <% if survey.questions? %>
      <div class="response-count">
        <%= pluralize(survey.responses.size, 'Response') unless survey.responses.blank? %>
      </div>
      <%= link_to "Take Survey", new_survey_response_path(survey.id), {class: "btn btn-default btn-sm active" }  %>
      <%= link_to "View Results", survey_path(survey.id), {class: "btn btn-default btn-sm active" } unless survey.responses.blank? %>
    <% else %>
      <%= link_to "Add Questions", edit_survey_path(survey.id), {class: "btn btn-default btn-sm active" }  %>
    <% end %>
  </div>
</li>

app/views/surveys/edit.html.erb
<%= render 'shared/nav' %>

<%= render 'shared/header', class_name1: 'inactive', class_name2: 'active' %>

<p>Next, fill in the questions.</p>

<%= render 'shared/survey_content', survey: @survey, class_name: ""%>

<hr>

<div class="sub-heading">Add a Question:</div>

<%= form_for @survey do |f| %>

  <div class="form-row">

    <div class="response-count">Choose which type of question to add.</div>

    <%= f.select(:question_type, options_for_select(Survey::QUESTION_TYPES.map.with_index{ |q, i| [q, i] })) %>

  </div>

  <%= f.submit("Add a New Question", class: 'btn btn-primary btn-lg btn-block') %>

<% end %>

<hr>

<%= render 'shared/existing_questions', class_name: ""  %>

app/views/surveys/index.html.erb
<header>
  <h1>Surveyor: <br>  Tell Me #allthethings!</h1>

  <p>Click on a survey below to take it or create one
   of your own!</p>

  <%= link_to "Create a New Survey", new_survey_path, {class: "btn btn-primary btn-lg btn-block" }  %>
</header>

<main>
  <div class="sub-heading underline padding">Take a Survey</div>
    <ol>
      <%= render(@surveys) || "There are no surveys available."  %>
    </ol>
</main>

app/views/surveys/new.html.erb
<%= render 'shared/nav' %>

<%= render 'shared/header', class_name1: 'active', class_name2: 'inactive' %>

<p>First, choose a title and description for your survey.</p>

<main>

  <%= form_for @survey do |f| %>

    <%= f.label :title, 'Survey Title' %>
    <%= f.text_field :title, placeholder: 'eg. "The personality test"'%>

    <%= f.label :description, 'Survey Description' %>
    <%= f.text_area :description, size: "30x4", placeholder: 'eg. "Discovering what is unique and special about all you crazy people"' %>

    <%= f.submit "Create Survey & Begin Adding Questions", class: 'btn btn-primary btn-lg btn-block' %>

  <% end %>

</main>

app/views/surveys/show.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/response_header', survey: @survey, title_text: "Results" %>

<div class="response-count">
  <%= pluralize(@survey.responses.size, 'Response') %>
</div>

<div class="response-form">
  <ol>
    <%= render partial: 'mcq_result', collection: @mcqs, as: :mcq %>
    <%= render partial: 'nrq_result', collection: @nrqs, as: :nrq %>
  </ol>
</div>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>